/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cardiograph_jni_JNI_Interface */

#ifndef _Included_com_cardiograph_jni_JNI_Interface
#define _Included_com_cardiograph_jni_JNI_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cardiograph_jni_JNI_Interface
 * Method:    getCInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cardiograph_jni_JNI_1Interface_getCInt
  (JNIEnv *, jclass);

/*
 * Class:     com_cardiograph_jni_JNI_Interface
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cardiograph_jni_JNI_1Interface_getCString
  (JNIEnv *, jclass);

/*
 * Class:     com_cardiograph_jni_JNI_Interface
 * Method:    trapper
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_cardiograph_jni_JNI_1Interface_trapper
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
