/*
 * MATLAB Compiler: 4.2 (R14SP2)
 * Date: Thu Nov 13 17:39:16 2014
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "-c"
 * "trapper1105.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_trapper1105_public_data[] = {'3', '0', '8', '1',
                                                       '9', 'D', '3', '0',
                                                       '0', 'D', '0', '6',
                                                       '0', '9', '2', 'A',
                                                       '8', '6', '4', '8',
                                                       '8', '6', 'F', '7',
                                                       '0', 'D', '0', '1',
                                                       '0', '1', '0', '1',
                                                       '0', '5', '0', '0',
                                                       '0', '3', '8', '1',
                                                       '8', 'B', '0', '0',
                                                       '3', '0', '8', '1',
                                                       '8', '7', '0', '2',
                                                       '8', '1', '8', '1',
                                                       '0', '0', 'C', '4',
                                                       '9', 'C', 'A', 'C',
                                                       '3', '4', 'E', 'D',
                                                       '1', '3', 'A', '5',
                                                       '2', '0', '6', '5',
                                                       '8', 'F', '6', 'F',
                                                       '8', 'E', '0', '1',
                                                       '3', '8', 'C', '4',
                                                       '3', '1', '5', 'B',
                                                       '4', '3', '1', '5',
                                                       '2', '7', '7', 'E',
                                                       'D', '3', 'F', '7',
                                                       'D', 'A', 'E', '5',
                                                       '3', '0', '9', '9',
                                                       'D', 'B', '0', '8',
                                                       'E', 'E', '5', '8',
                                                       '9', 'F', '8', '0',
                                                       '4', 'D', '4', 'B',
                                                       '9', '8', '1', '3',
                                                       '2', '6', 'A', '5',
                                                       '2', 'C', 'C', 'E',
                                                       '4', '3', '8', '2',
                                                       'E', '9', 'F', '2',
                                                       'B', '4', 'D', '0',
                                                       '8', '5', 'E', 'B',
                                                       '9', '5', '0', 'C',
                                                       '7', 'A', 'B', '1',
                                                       '2', 'E', 'D', 'E',
                                                       '2', 'D', '4', '1',
                                                       '2', '9', '7', '8',
                                                       '2', '0', 'E', '6',
                                                       '3', '7', '7', 'A',
                                                       '5', 'F', 'E', 'B',
                                                       '5', '6', '8', '9',
                                                       'D', '4', 'E', '6',
                                                       '0', '3', '2', 'F',
                                                       '6', '0', 'C', '4',
                                                       '3', '0', '7', '4',
                                                       'A', '0', '4', 'C',
                                                       '2', '6', 'A', 'B',
                                                       '7', '2', 'F', '5',
                                                       '4', 'B', '5', '1',
                                                       'B', 'B', '4', '6',
                                                       '0', '5', '7', '8',
                                                       '7', '8', '5', 'B',
                                                       '1', '9', '9', '0',
                                                       '1', '4', '3', '1',
                                                       '4', 'A', '6', '5',
                                                       'F', '0', '9', '0',
                                                       'B', '6', '1', 'F',
                                                       'C', '2', '0', '1',
                                                       '6', '9', '4', '5',
                                                       '3', 'B', '5', '8',
                                                       'F', 'C', '8', 'B',
                                                       'A', '4', '3', 'E',
                                                       '6', '7', '7', '6',
                                                       'E', 'B', '7', 'E',
                                                       'C', 'D', '3', '1',
                                                       '7', '8', 'B', '5',
                                                       '6', 'A', 'B', '0',
                                                       'F', 'A', '0', '6',
                                                       'D', 'D', '6', '4',
                                                       '9', '6', '7', 'C',
                                                       'B', '1', '4', '9',
                                                       'E', '5', '0', '2',
                                                       '0', '1', '1', '1'
                                                       , '\0'};

const char *__MCC_trapper1105_name_data = "trapper1105";

const char *__MCC_trapper1105_root_data = "";

const unsigned char __MCC_trapper1105_session_data[] = {'7', '6', '3', 'D',
                                                        '3', 'C', '2', '6',
                                                        '9', '0', 'E', 'C',
                                                        'F', '4', 'F', '4',
                                                        '7', '4', '3', 'A',
                                                        '2', '2', '1', '9',
                                                        'C', '2', '9', 'C',
                                                        'B', '3', '2', '8',
                                                        '4', 'C', 'F', 'F',
                                                        '2', 'A', 'E', '3',
                                                        'F', 'C', '6', 'E',
                                                        'B', 'F', 'C', '6',
                                                        'E', 'F', 'C', 'F',
                                                        'B', '7', '1', '2',
                                                        '8', 'E', '4', '2',
                                                        'E', 'C', '5', 'F',
                                                        'C', '5', 'D', '8',
                                                        '6', '2', 'B', 'F',
                                                        '6', '4', '1', 'D',
                                                        '4', 'E', '2', '1',
                                                        '6', 'F', '0', 'A',
                                                        '8', 'C', '7', '0',
                                                        '0', 'D', 'E', '8',
                                                        '7', '5', 'B', 'C',
                                                        '1', '3', '1', '5',
                                                        '8', '7', 'E', '4',
                                                        '9', 'C', '1', '7',
                                                        'B', 'B', '9', '8',
                                                        '1', '9', '6', '6',
                                                        'E', 'C', '2', 'C',
                                                        'C', '5', 'C', '0',
                                                        '6', '1', '5', '1',
                                                        '4', '5', '7', 'D',
                                                        '3', '5', '8', '3',
                                                        'D', '0', '5', '5',
                                                        'C', 'C', 'C', 'D',
                                                        '1', '0', 'E', '0',
                                                        'B', '5', '4', 'F',
                                                        '4', '5', 'B', 'F',
                                                        '6', 'C', '2', '3',
                                                        '9', '1', 'B', '9',
                                                        '6', '2', '5', '1',
                                                        '1', 'F', '8', '1',
                                                        '2', '3', '6', 'A',
                                                        '0', '8', '3', 'F',
                                                        '0', '5', '1', 'A',
                                                        '2', '3', '6', '6',
                                                        'C', '8', '5', 'C',
                                                        'F', '0', 'A', '8',
                                                        '0', 'B', '3', '7',
                                                        '4', '7', '2', '7',
                                                        '2', '5', '6', '8',
                                                        'B', '7', '8', '5',
                                                        'D', '0', '9', '3',
                                                        'D', '7', 'F', '8',
                                                        'B', '2', '3', '9',
                                                        '7', '1', '7', '4',
                                                        '6', 'B', '9', 'B',
                                                        'E', '6', '8', 'D',
                                                        'D', 'E', '1', '6',
                                                        '8', 'B', '1', '2',
                                                        '4', 'B', 'F', 'D',
                                                        'A', 'D', 'B', 'D',
                                                        'D', '7', '8', 'E'
                                                        , '\0'};

const char *__MCC_trapper1105_matlabpath_data[] = {"trapper1105/", "work/",
                                                   "toolbox/compiler/deploy/",
                                                   "$TOOLBOXMATLABDIR/general/",
                                                   "$TOOLBOXMATLABDIR/ops/",
                                                   "$TOOLBOXMATLABDIR/lang/",
                                                   "$TOOLBOXMATLABDIR/elmat/",
                                                   "$TOOLBOXMATLABDIR/elfun/",
                                                   "$TOOLBOXMATLABDIR/specfun/",
                                                   "$TOOLBOXMATLABDIR/matfun/",
                                                   "$TOOLBOXMATLABDIR/datafun/",
                                                   "$TOOLBOXMATLABDIR/polyfun/",
                                                   "$TOOLBOXMATLABDIR/funfun/",
                                                   "$TOOLBOXMATLABDIR/sparfun/",
                                                   "$TOOLBOXMATLABDIR/scribe/",
                                                   "$TOOLBOXMATLABDIR/graph2d/",
                                                   "$TOOLBOXMATLABDIR/graph3d/",
                                                   "$TOOLBOXMATLABDIR/specgraph/",
                                                   "$TOOLBOXMATLABDIR/graphics/",
                                                   "$TOOLBOXMATLABDIR/uitools/",
                                                   "$TOOLBOXMATLABDIR/strfun/",
                                                   "$TOOLBOXMATLABDIR/imagesci/",
                                                   "$TOOLBOXMATLABDIR/iofun/",
                                                   "$TOOLBOXMATLABDIR/audiovideo/",
                                                   "$TOOLBOXMATLABDIR/timefun/",
                                                   "$TOOLBOXMATLABDIR/datatypes/",
                                                   "$TOOLBOXMATLABDIR/verctrl/",
                                                   "$TOOLBOXMATLABDIR/codetools/",
                                                   "$TOOLBOXMATLABDIR/helptools/",
                                                   "$TOOLBOXMATLABDIR/winfun/",
                                                   "$TOOLBOXMATLABDIR/demos/",
                                                   "$TOOLBOXMATLABDIR/timeseries/",
                                                   "$TOOLBOXMATLABDIR/hds/",
                                                   "toolbox/local/",
                                                   "toolbox/shared/optimlib/",
                                                   "toolbox/database/database/",
                                                   "toolbox/compiler/",
                                                   "toolbox/optim/",
                                                   "toolbox/signal/signal/",
                                                   "toolbox/signal/sigtools/"};
const int __MCC_trapper1105_matlabpath_data_count = 40;

const char *__MCC_trapper1105_classpath_data[] = {"java/jar/toolbox/database.jar"};
const int __MCC_trapper1105_classpath_data_count = 1;

const char *__MCC_trapper1105_lib_path_data[] = { "" };
const int __MCC_trapper1105_lib_path_data_count = 0;

const char *__MCC_trapper1105_mcr_application_options[] = { "" };
const int __MCC_trapper1105_mcr_application_option_count = 0;
const char *__MCC_trapper1105_mcr_runtime_options[] = { "" };
const int __MCC_trapper1105_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


